version: '3'
services:
  app:
    container_name: beequeue
    restart: always
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - redis
    links:
      - redis     
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379' 
      
       